version: '3.9'
services:
  frontend:
    build:
      context: ./frontend

  backend:
    build:
      context: ./backend

  reverse-proxy:
    build:
      context: ./reverse-proxy
    ports:
      - ${NGINX_PORT}:80
